# Generated by Django 4.2.3 on 2023-07-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoubleEliminationBracket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scheduled", models.DateTimeField()),
                ("home_score", models.IntegerField(default=0)),
                ("visitor_score", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("matches", models.ManyToManyField(to="tournament.match")),
            ],
        ),
        migrations.RemoveField(
            model_name="team",
            name="tournament",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Tournament",
        ),
        migrations.AddField(
            model_name="match",
            name="home_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home_matches",
                to="tournament.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="visitor_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitor_matches",
                to="tournament.team",
            ),
        ),
        migrations.AddField(
            model_name="doubleeliminationbracket",
            name="lower_bracket_rounds",
            field=models.ManyToManyField(
                related_name="lower_bracket", to="tournament.round"
            ),
        ),
        migrations.AddField(
            model_name="doubleeliminationbracket",
            name="upper_bracket_rounds",
            field=models.ManyToManyField(
                related_name="upper_bracket", to="tournament.round"
            ),
        ),
    ]
